name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "0 14 * * 1-5" # every weekday at 9am CT (2pm UTC)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install gcc libncurses5-dev libncursesw5-dev
    - name: Collect kernel info
      run: uname -r
    - name: Collect GCC version
      run: gcc --version
    - name: make
      run: make
